CREATE TABLE IF NOT EXISTS "Station" (
  "id" SERIAL PRIMARY KEY,
  "name" VARCHAR(128) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS "Tag" (
  "stationId" INTEGER NOT NULL,
  "title" VARCHAR(32) NOT NULL,
  UNIQUE ("stationId", "title")
);
